language: go

go:
  - "1.12.x"
  - tip

dist: xenial
sudo: required
services:
  - docker

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on GO_TESTPROXY_DEBUG=true

install:
  - go mod download

script:
  - go test -v ./...